# Site settings
title: "Tech Committee"
subtitle: "SHPE UCF"
email: tech.shpeucf@gmail.com
repository: "shpeucf/apptutorial"
description: >- # this means to ignore newlines until "baseurl:"
  Site for members to learn about react-native and all its features.
logo: "/assets/images/shpe-logo.png"
# masthead_title: "Tech Website"
timezone: America/New_York
breadcrumbs: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
github: [metadata]

include:
- _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/SHPEUCF/apptutorial"
    - label: "Bugs"
      icon: "fas fa-bug"
      url: "https://github.com/SHPEUCF/apptutorial/issues"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"
